### ISSUE TITLE
variáveis das dicas

### ISSUE THREAD

**Issue by arthurdelmas** [camila-ito/ex6b-grupo01#6]
Pessoal, lembrem de colocar as variáveis das dicas, com representações diferentes das variáveis do resto do programa para não dar conflito.

**Comment by camila-ito** [comment]
não esqueçam de coloca cada pessoa de acordo com a ordem alfabética e fixas no local dela para não dar problema no final

**Comment by priscilasousa** [comment]
Ótimo, bem lembrado. Vamos fazer isso sim.
